name: monorepository
description: A Dart package for managing monorepository. **Coming Soon!**
version: 0.0.0
homepage: https://github.com/antinna/monorepo
repository: https://github.com/antinna/monorepo
issue_tracker: https://github.com/antinna/monorepo/issues
documentation: https://github.com/antinna/monorepo#readme
license: MIT

screenshots:
  - description: Antinna Logo
    path: screenshots/antinna_copyrights.webp

funding:
  - https://github.com/sponsors/Manishmg3994

social:
  github: antinna
  youtube: https://www.youtube.com/@antinna

environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

# Define some useful topics related to your package
topics:
  - monorepo
  - modular-development
  - build-system
  - repository-organization
  - tooling


# Optional: Add maintainers if you have collaborators
maintainers:
  - "Manish Gautam <manishgautammg7@gmail.com>"
